contacts GET and POST endpoints
alkemyTech/OT109-Server pull request #23
Opened 2021-12-04 05:06 UTC by dellmdq

Para validar los campos de email y phone, creé una clase ValidatorUtil en un nuevo package Utils. Cree una clase de configuración para obtener un bean en el package config.

Creados DTOS para los request del post y el get(all).  A su vez cree los métodos de pasaje de los dtos a la clase correspondiente para evitar boilerplate code.

Falta aplicar la lógica de seguridad.

2021-12-04 18:59 UTC, nicotruk commented
Corregir...

Enviando:
![Screenshot from 2021-12-04 15-44-34](https://user-images.githubusercontent.com/17879377/144721366-d07b2628-954a-4f47-860b-e2fa1cd14a66.png)

Devuelve:
![Screenshot from 2021-12-04 15-44-40](https://user-images.githubusercontent.com/17879377/144721371-e6653de1-81c3-498c-ae2f-7be0b4752fd8.png)

2021-12-04 18:59 UTC, nicotruk requested changes

2021-12-04 18:59 UTC, nicotruk commented on src/main/java/com/alkemy/ong/controllers/ContactController.java
> +        if(contactPostDto.getName().isEmpty()) {
Posible NullPointer

2021-12-04 23:04 UTC, dellmdq commented on src/main/java/com/alkemy/ong/controllers/ContactController.java
> +        if(contactPostDto.getName().isEmpty()) {
Nico, consulta. Como podría mejorar las validaciones del ContactPostDTO para que no queden los if en el controller. Estaría bien crear un método de validación específico al ContactPostDTO?
![image](https://user-images.githubusercontent.com/45313969/144727242-a3306293-226a-4a2f-9fcc-559d4d169d29.png)

Ya estoy viendo para arreglar el NP.

2021-12-05 01:20 UTC, dellmdq commented on src/main/java/com/alkemy/ong/controllers/ContactController.java
> +        if(contactPostDto.getName().isEmpty()) {
Nico disculpas por subir el código así! No testee el endpoint, cualquiera.
Lo pusheé ayer a la madrugada medio dormido.
Creo que están manejados los errores más probables. Por otro caso si tenés algún consejo para corregir los ifs ahí que quedan horribles porfa avisame. 
![image](https://user-images.githubusercontent.com/45313969/144729644-2b578aa4-d2ea-49a6-bb5f-bb681b7c7979.png)

2021-12-06 00:28 UTC, nicotruk commented
Tu codigo ahora cumple con lo esperado.

Lo que te pasa con los ifs es que no te esta evaluando las condiciones de @NotEmpty que pusiste sobre el objeto que recibe controlador en tu metodo create. Para que se evaluen, deberias agregar al lado de @RequestBody un @Valid

Eso hace que se evaluen las condiciones y si no se cumplen, lanza una excepcion de tipo MethodArgumentNotValidException (que deberias capturar para mostrar un mensaje mas lindo y simple)

2021-12-06 00:28 UTC, merged

2021-12-06 20:38 UTC, dellmdq commented
Gracias por lo del @Valid yo pensé que se veficaban de una. Ahí estoy viendo para mejorar un poco este código y hacerlo más prolijo. 
Agregue @Valid y ví que cuando mandas el campo vacío el mensaje de respuesta es distinto, la excepción MethodArgumentNotValidException la captura el ExceptionHandlerExceptionResolver y muestra el mensaje.